version: 1.0.{build}

branches:
  only:
    - master

shallow_clone: true

clone_depth: 1

image:
  - Visual Studio 2015 #VSVER {9,10,11,12,14}.0
  # - Visual Studio 2017 #VSVER ^^^^^^^^^^^^^^^^^ (msvc_2017 > program_files/msvs/2017)
  
environment:
  matrix:
    # visual studio 2013
    # qt 5.{3,4}
    # qt 5.5
#    - QTDIR: C:\Qt\5.5\msvc2013
#      cname: Win32-VS2013
#      VSVER: 12
#    - QTDIR: C:\Qt\5.5\msvc2013_64
#      cname: Win64-VS2013
#      VSVER: 12
#    # qt 5.6
#    - QTDIR: C:\Qt\5.6\msvc2013
#      cname: Win32-VS2013
#      VSVER: 12
#    - QTDIR: C:\Qt\5.6\msvc2013_64
#      cname: Win64-VS2013
#      VSVER: 12
#    # qt 5.7
#    - QTDIR: C:\Qt\5.7\msvc2013
#      cname: Win32-VS2013
#      VSVER: 12
#    - QTDIR: C:\Qt\5.7\msvc2013_64
#      cname: Win64-VS2013
#      VSVER: 12
#    # qt 5.8
#    - QTDIR: C:\Qt\5.8\msvc2013
#      cname: Win32-VS2013
#      VSVER: 12
#    - QTDIR: C:\Qt\5.8\msvc2013_64
#      cname: Win64-VS2013
#      VSVER: 12
    # visual studio 2015
    # qt 5.6
    # - QTDIR: C:\Qt\5.6\msvc2015
    #   cname: Win32-VS2015
    #   VSVER: 14
    # - QTDIR: C:\Qt\5.6\msvc2015_64
    #   cname: Win64-VS2015
    #   VSVER: 14
    # qt 5.7 only 32 bit
    # qt 5.9
    - QTDIR: C:\Qt\5.9\msvc2015
      cname: Win32-VS2015
      VSVER: 14
    - QTDIR: C:\Qt\5.9\msvc2015_64
      cname: Win64-VS2015
      VSVER: 14
    # qt 5.10
    - QTDIR: C:\Qt\5.10\msvc2015
      cname: Win32-VS2015
      VSVER: 14
    - QTDIR: C:\Qt\5.10\msvc2015_64
      cname: Win64-VS2015
      VSVER: 14
    # qt 5.11
    - QTDIR: C:\Qt\5.11\msvc2015
      cname: Win32-VS2015
      VSVER: 14
    - QTDIR: C:\Qt\5.11\msvc2015_64
      cname: Win64-VS2015
      VSVER: 14
    # visual studio 2017
    # %QTDIR%\bin\qtenv2.bat not found
    # qt 5.12
    # - QTDIR: C:\Qt\5.12\msvc2017
    #   cname: Win32-VS2017
    #   VSVER: 15
    # - QTDIR: C:\Qt\5.12\msvc2017_64
    #   cname: Win64-VS2017
    #   VSVER: 15

matrix:
  exclude:
#   - image: Visual Studio 2013
#     VSVER: 14
#   - image: Visual Studio 2013
#     VSVER: 15
    - image: Visual Studio 2015
      VSVER: 12
    - image: Visual Studio 2015
      VSVER: 15
    # - image: Visual Studio 2017
    #   VSVER: 12
    # - image: Visual Studio 2017
    #   VSVER: 14
# fast_finish: true
  # allow_failures:
  #   - cname: Win64-VS2017

install:
# init qt environment
  - '%QTDIR%\bin\qtenv2.bat'
# init windows sdk
# SDKs\2013:{Azure,Windows\{6.0a,7.0,7.1}},2015:{Azura,Service Fabric,Windows},2017:{Azure,Service Fabric}
  - if %QTDIR:_64=%==%QTDIR% ( set ARCH=x86 ) else set ARCH=x64
  - if %ARCH%==x64 if not %VSVER%==15 call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
# init Visual Studio environment
  - ps: >-
        If ($env:VSVER -Match "15") {
            $env:VSINIT="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat"
        } Else {
            $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
            $env:VSINIT="%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat"
        }
  - echo "Using Visual Studio %VSVER% at %VSCOMNTOOLS%"
  - call "%VSINIT%" %ARCH%

before_build:
  - if %ARCH%==x86 (set VCPKG_DEFAULT_TRIPLET=x86-windows) else (set VCPKG_DEFAULT_TRIPLET=x64-windows)
  - vcpkg install freetype libpng zlib

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake -Wno-dev -G "Visual Studio %VSVER%"       -B build-win32 -DCMAKE_TOOLCHAIN_FILE=C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake .
  - cmake -Wno-dev -G "Visual Studio %VSVER% Win64" -B build-win64 -DCMAKE_TOOLCHAIN_FILE=C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake .
  - cmake --build build-win32 --config Release
  - cmake --build build-win64 --config Release
    # copy Qt DLL into bin
  - copy %QTDIR%\bin\Qt5Core.dll    %APPVEYOR_BUILD_FOLDER%
  - copy %QTDIR%\bin\Qt5Gui.dll     %APPVEYOR_BUILD_FOLDER%
  - copy %QTDIR%\bin\Qt5Xml.dll     %APPVEYOR_BUILD_FOLDER%
  - copy %QTDIR%\bin\Qt5OpenGL.dll  %APPVEYOR_BUILD_FOLDER%
  - copy %QTDIR%\bin\Qt5Widgets.dll %APPVEYOR_BUILD_FOLDER%
  - mkdir %APPVEYOR_BUILD_FOLDER%\platforms
  - copy %QTDIR%\plugins\platforms\qwindows.dll %APPVEYOR_BUILD_FOLDER%\platforms

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - copy "%VCINSTALLDIR%\redist\x86\Microsoft.VC140.CRT\vcruntime140.dll" build-win32
  - copy "%VCINSTALLDIR%\redist\x64\Microsoft.VC140.CRT\vcruntime140.dll" build-win64
  - 7z a build-win32.zip build-win32
  - 7z a build-win64.zip build-win64

artifacts:
  - path: build-win32.zip
    name: Xpdf-win32
  - path: build-win64.zip
    name: Xpdf-win64
cache: 
  - c:\tools\vcpkg\installed\
